### ISSUE TITLE
Initialize project

### ISSUE THREAD

**Issue by kj666** [kevin-tan/Q-AWebApplication#1]
Initialize dependencies: frameworks, springboot, AngularJS, maven

**Comment by kj666** [comment]
Setting up the back end server

**Comment by kj666** [comment]
Set up Database (Mysql)

**Comment by BiscottiBoys** [comment]
Create log in page, registration page, QA page

**Comment by kevin-tan** [comment]
I initialized the project with the dependencies, as well as the .gitignore file. The pom.xml contains two commented dependencies the security and JPA, Luca will enable the JPA when he is done setting up the connection to mySQL and i will enable security when i implement the login.
