### ISSUE TITLE
Design for votes on replies and question

### ISSUE THREAD

**Issue by kevin-tan** [kevin-tan/Q-AWebApplication#12]
Currently I am thinking of two possible ways to implement the vote mechanism on a post,
1. Implement two integers which are upVotes and downVotes, or
2. Implement a Vote model which itself will have those two properties

What do you guys prefer?

Related to:
- Issue #15

**Comment by ShawnGuerra-Bautista** [comment]
What are the implications of choosing one over another?

**Comment by SagarPatel43** [comment]
I think it would be a better design choice to go with the Vote model, with the upvotes/downvotes in one place we can calculate the total votes and most importantly this design would limit coupling

**Comment by kevin-tan** [comment]
@ShawnGuerra-Bautista like sagar said, it will decrease coupling which allows for more maintainability and testing in the future

**Comment by kevin-tan** [comment]
We will use Vote model to represent the upvotes/downvotes/totalvotes as per issue #15 .
