### ISSUE TITLE
Changing Front-End Tools

### ISSUE THREAD

**Issue by ShawnGuerra-Bautista** [kevin-tan/Q-AWebApplication#13]
So, for the last few days, I've been trying to learn Angular2 (version 5), but the learning curve, especially if we aren't familiar with TypeScript, is a bit too steep for implementing our features within less than a week. Moreover, since this is a small project, Angular2 is a little overkill.

So, there are two options for the framework we can use: ReactJS and VueJS.  VueJS might be the most appropriate option for this project as it is the easiest and simplest to learn. However, practically, ReactJS is more beneficial to learn in the long run.

Just a quick note: we do not need a JavaScript framework, but it would make life easier if we wanted to do some interactive features on the client-side.

For the CSS framework, we will be using Bootstrap.

**Comment by ShawnGuerra-Bautista** [comment]
Since Vue isn't compatible with REST without any 3rd party support, we are going to either use JQuery or Angular. We are going to have more time during our next sprint, so learning Angular starting next week is not too bad compared to now when we have to present something on Friday.

**Comment by kevin-tan** [comment]
AngularJS would be preferable  we want to use as our frontend with our backend

**Comment by ShawnGuerra-Bautista** [comment]
I'm pretty sure Angular5 does work well with Spring. I'll fill in the details later.
