### ISSUE TITLE
Q&A Page

### ISSUE THREAD

**Issue by kevin-tan** [kevin-tan/Q-AWebApplication#19]
Implement the Q&A dashboard page on the client side.

Related to:
- Issue #3

**Comment by BiscottiBoys** [comment]
Slight confusion on my part, Shawn will be taking care of this issue which includes the dashboard page where a list of questions are displayed (we can decide on which tickets to display).

**Comment by BiscottiBoys** [comment]
I am back on this issue

**Comment by kevin-tan** [comment]
Duplicate ticket
