### ISSUE TITLE
Setup database

### ISSUE THREAD

**Issue by kj666** [kevin-tan/Q-AWebApplication#2]
Set up online database with mySQL and hosting using GearHost

**Comment by kevin-tan** [comment]
@luca1030 when do you think you'll be able to set it up? while we wait for you to set it up, i can use the h2 in-memory database for now until you set it up and delete it once you're done.

**Comment by luca1030** [comment]
@kevin-tan i created a gearhost account yesterday and created a database for mysql. I was getting errors linking mysql and gearhost yesterday and I m investigating the issue now should have a fix soon.

**Comment by kevin-tan** [comment]
@luca1030 alright sounds good.
