### ISSUE TITLE
Create header and footer templates

### ISSUE THREAD

**Issue by BiscottiBoys** [kevin-tan/Q-AWebApplication#22]
Implement header and footer templates for html pages on client side.

Note:
- I saw that the welcome and homepage both have a nice top nav bar and bottom disclaimer. I started using these items on my page, maybe we should turn then into our defaults?

Related to:
- Issue #65

**Comment by ShawnGuerra-Bautista** [comment]
Yes, it will be implemented with Angular as a component.
