### ISSUE TITLE
Q&A page - open for work

### ISSUE THREAD

**Issue by ShawnGuerra-Bautista** [kevin-tan/Q-AWebApplication#37]
Due to my condition and lack of abilities, the Question page might not be complete even if I tried working on it before the deadline. Therefore, I will leave the Q&A page open for anyone that wants to work on it; the incomplete work involves JQuery. I uploaded my work on the Shawn_Question branch. 

The incomplete work is in "\src\main\java\frontend\app\question". I provided some comments to where I would put the JQuery.

I apologies for the big inconvenience.

Regards,
Shawn Guerra-Bautista

**Comment by kevin-tan** [comment]
Ticket #24 has been moved to sprint 2. if you can't finish a issue by a sprint please move it to the next.
