### ISSUE TITLE
Fix issue where replies can be done without a question

### ISSUE THREAD

**Issue by kevin-tan** [kevin-tan/Q-AWebApplication#38]
Fix issue where replies can be done without a question that has been posted.

Related to:
- Issue #5 
- Issue #11 
- Issue #26

**Comment by ShawnGuerra-Bautista** [comment]
May you clarify on this issue.

Don't we need to be in the Question page to actually reply?

**Comment by kevin-tan** [comment]
As stated in the title and label, the current bug corresponds to the fact that we can post an answer without a question.
