### ISSUE TITLE
Unified front end branch to work off

### ISSUE THREAD

**Issue by BiscottiBoys** [kevin-tan/Q-AWebApplication#43]
Lets tidy up our current front end branches, push them back onto git and then merge them into a "front-end-master" from which we can implement our interactions with the back end. What do you guys think? I can take a stab at this tomorrow.

@ShawnGuerra-Bautista @kj666 @shuridbiswas

**Comment by kevin-tan** [comment]
You should tidy your branches do a pull request and then merge them to master so everyone in the team will have the same working copy

**Comment by BiscottiBoys** [comment]
Will do, we will get the front end tidied and merged into master this weekend.
